"""Create booking_with_room table

Revision ID: ca393f5cc40d
Revises: 1d257cadb2d0
Create Date: 2023-12-23 22:51:44.328379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca393f5cc40d'
down_revision: Union[str, None] = '1d257cadb2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_with_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('arrivalDate', sa.Date(), nullable=False),
    sa.Column('departureDate', sa.Date(), nullable=False),
    sa.Column('numbersOfPeople', sa.Integer(), nullable=False),
    sa.Column('room_cost', sa.Numeric(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'room_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_with_room')
    # ### end Alembic commands ###
