"""create client table

Revision ID: 38161c0016c8
Revises: 99e269bee848
Create Date: 2023-12-23 22:22:04.910446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38161c0016c8'
down_revision: Union[str, None] = '99e269bee848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_fullName', sa.String(), nullable=False),
    sa.Column('client_adress', sa.String(), nullable=False),
    sa.Column('client_phone_number', sa.String(), nullable=False),
    sa.Column('client_bithday', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
 